/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnalyzeRouteImport } from './routes/analyze'
import { Route as ChordsRouteImport } from './routes/chords'
import { Route as LiveRouteImport } from './routes/live'
import { Route as TunerRouteImport } from './routes/tuner'
import { Route as ApiChordminiRouteImport } from './routes/api/chordmini'
import { Route as SongIdRouteImport } from './routes/song.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyzeRoute = AnalyzeRouteImport.update({
  id: '/analyze',
  path: '/analyze',
  getParentRoute: () => rootRouteImport,
} as any)
const ChordsRoute = ChordsRouteImport.update({
  id: '/chords',
  path: '/chords',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveRoute = LiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => rootRouteImport,
} as any)
const TunerRoute = TunerRouteImport.update({
  id: '/tuner',
  path: '/tuner',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChordminiRoute = ApiChordminiRouteImport.update({
  id: '/api/chordmini',
  path: '/api/chordmini',
  getParentRoute: () => rootRouteImport,
} as any)
const SongIdRoute = SongIdRouteImport.update({
  id: '/song/$id',
  path: '/song/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analyze': typeof AnalyzeRoute
  '/chords': typeof ChordsRoute
  '/live': typeof LiveRoute
  '/tuner': typeof TunerRoute
  '/api/chordmini': typeof ApiChordminiRoute
  '/song/$id': typeof SongIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analyze': typeof AnalyzeRoute
  '/chords': typeof ChordsRoute
  '/live': typeof LiveRoute
  '/tuner': typeof TunerRoute
  '/api/chordmini': typeof ApiChordminiRoute
  '/song/$id': typeof SongIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analyze': typeof AnalyzeRoute
  '/chords': typeof ChordsRoute
  '/live': typeof LiveRoute
  '/tuner': typeof TunerRoute
  '/api/chordmini': typeof ApiChordminiRoute
  '/song/$id': typeof SongIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analyze'
    | '/chords'
    | '/live'
    | '/tuner'
    | '/api/chordmini'
    | '/song/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analyze'
    | '/chords'
    | '/live'
    | '/tuner'
    | '/api/chordmini'
    | '/song/$id'
  id:
    | '__root__'
    | '/'
    | '/analyze'
    | '/chords'
    | '/live'
    | '/tuner'
    | '/api/chordmini'
    | '/song/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyzeRoute: typeof AnalyzeRoute
  ChordsRoute: typeof ChordsRoute
  LiveRoute: typeof LiveRoute
  TunerRoute: typeof TunerRoute
  ApiChordminiRoute: typeof ApiChordminiRoute
  SongIdRoute: typeof SongIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analyze': {
      id: '/analyze'
      path: '/analyze'
      fullPath: '/analyze'
      preLoaderRoute: typeof AnalyzeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chords': {
      id: '/chords'
      path: '/chords'
      fullPath: '/chords'
      preLoaderRoute: typeof ChordsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live': {
      id: '/live'
      path: '/live'
      fullPath: '/live'
      preLoaderRoute: typeof LiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tuner': {
      id: '/tuner'
      path: '/tuner'
      fullPath: '/tuner'
      preLoaderRoute: typeof TunerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chordmini': {
      id: '/api/chordmini'
      path: '/api/chordmini'
      fullPath: '/api/chordmini'
      preLoaderRoute: typeof ApiChordminiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/song/$id': {
      id: '/song/$id'
      path: '/song/$id'
      fullPath: '/song/$id'
      preLoaderRoute: typeof SongIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyzeRoute: AnalyzeRoute,
  ChordsRoute: ChordsRoute,
  LiveRoute: LiveRoute,
  TunerRoute: TunerRoute,
  ApiChordminiRoute: ApiChordminiRoute,
  SongIdRoute: SongIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
